### ISSUE TITLE
Icons color based on whether on battery or charger

### ISSUE THREAD

**Issue by Gaurav-Original-ClassicShellTester** [tarcode-apps/BatteryMode#35]
A feature to show icons color based on whether on battery or charger.

On charger/charging=green
On battery but above say e.g. 5%=yellow
On battery but only below 5% (critical battery level)=red.

**Comment by advait404** [comment]
The coloring can be similar to the "Battery Percentage - Pure Battery add-on" app. The icon is white when not charging, green when charging, and red when on low bettery. 
It would be great if this coloring scheme applies when the "Display charge percentage in tray" is enabled.

**Comment by artar94** [comment]
@Gaurav-Original-ClassicShellTester @advait404 Please try this beta version https://dl.tarcode.ru/beta/4.2.0.179 and tell me if the implementation suits you?

**Comment by advait404** [comment]
Thank you for the update!
It does work as intended, but I would like to make some suggestions:
1. change the green colour into a darker tone. It would be better if the green is changed to be more easily visible, since the current tone is too close to white and a bit difficult to see at first glance. Below, you can see how the '89' is coloured and is easily visible. This colour would be better for the BatteryMode icons.
![image](https://user-images.githubusercontent.com/83760070/144161319-049e954b-3daf-414f-a3e4-5946299a852f.png)

2. font size for when “Display charge percentage in tray” can be increased. The one on the right is BatteryMode, and it would be better if it looks similar to the one on the left.
![image](https://user-images.githubusercontent.com/83760070/144161692-6779e105-f696-487c-a97a-a91c5b048a85.png)

3. A way to set custom low battery/red icon value. I wasn't able to properly test the icon turning red, as my battery is very degraded. But having an option to set a 'warning' battery level to change the icon colour to red would be great.

Hopefully these suggestions aren't too much troublesome to implement, and thank you very much for this amazing software!

**Comment by artar94** [comment]
@advait404 Sorry for the long replies, I don't have time for this project at all. You can try your suggestions in this beta https://dl.tarcode.ru/beta/4.2.0.181

**Comment by advait404** [comment]
Thank you very much for the update, the program exactly as intended.

**Comment by Gaurav-Original-ClassicShellTester** [comment]
@artar94 I am sorry for the very late reply but the changes you did are simply fantastic and they work for me perfectly. Thank you so much for a great app. I am telling everyone about it. It was so much needed since Windows 7.
