### ISSUE TITLE
Icons for Windows 11

### ISSUE THREAD

**Issue by byyxx128** [tarcode-apps/BatteryMode#44]
With [v4.2.0.178](https://github.com/tarcode-apps/BatteryMode/releases/tag/v4.2.0.178), Windows 11 icon has been added.
Windows 11 Light is added since [4.2.0.179](https://dl.tarcode.ru/beta/4.2.0.179).

**Comment by artar94** [comment]
@byyxx128 Please try this beta version https://dl.tarcode.ru/beta/4.2.0.179
> why the `Use crossed icon when the battery is missing` is unavailable?

For Windows 11, I only painted one variation of this icon.

**Comment by byyxx128** [comment]
The version [4.2.0.179](https://dl.tarcode.ru/beta/4.2.0.179) is good.

I still think the crossed icon is necessary when the battery is unavailable.

Hopefully you would paint the variation of Win11 icon if possible.

**Comment by byyxx128** [comment]
Thanks for fixing the Win11 icons. The version [4.2.0.179](https://dl.tarcode.ru/beta/4.2.0.179) is good.

I still think the crossed icon is necessary when the battery is unavailable.

Hopefully you would paint the variation of Win11 icon if possible.

**Comment by artar94** [comment]
There used to be two variations of these icons:
![image](https://user-images.githubusercontent.com/5181651/144224735-6ca213e8-dc91-4b09-b7b8-cfa71aa556f8.png)
Now Microsoft has ditched semi-transparent icons and I only left this icon for the missing battery:
![image](https://user-images.githubusercontent.com/5181651/144224797-5f997c7f-39bc-4b2a-a47f-82a97149660f.png)
I think this icon will be enough.
Setting `Use crossed icon when the battery is missing` is unavailable because it does not affect anything. It doesn't matter if it is on or off, but the icon will always be crossed out.

**Comment by byyxx128** [comment]
Got that. Actually, the only icon for the missing battery is enough. I used to think there was not any icon to show the missing battery... But there is. Alright.

BYW, do we need to move the cross a little to the right? I am not sure what the original icon from Microsoft is, but I guess it would be better if the cross is showed fully. But if it matches the original icon of Windows 11, just keep it.
