### ISSUE TITLE
wrong color for ultimate performance in task bar

### ISSUE THREAD

**Issue by madgoatz** [tarcode-apps/BatteryMode#62]
the ultimate performance color is purple, but the taskbar icon is white when it is on ultimate performance.... only the vista theme shows purple for it and also shows purple for the vista balance performance

![image](https://user-images.githubusercontent.com/88365986/161292804-fc35533c-6dbf-4b10-bc24-daf714552434.png)
![image](https://user-images.githubusercontent.com/88365986/161292254-a97f2fd7-50c8-4ec3-be29-ad8ac448efec.png)

**Comment by artar94** [comment]
@madgoatz Please specify the Battery Mode version.

**Comment by artar94** [comment]
@madgoatz Please run the command `powercfg /list` on the command line and write the result to me.

**Comment by madgoatz** [comment]
Existing Power Schemes (* Active)
-----------------------------------
Power Scheme GUID: 381b4222-f694-41f0-9685-ff5bb260df2e  (Balanced)
Power Scheme GUID: 4e5bddd9-75ad-4f4e-925e-78d8fdbedf94  (Ultimate Performance) *
Power Scheme GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c  (High performance)
Power Scheme GUID: a1841308-3541-4fab-bc81-f71556f20b4a  (Power saver)

**Comment by artar94** [comment]
@madgoatz It looks like the Ultimate Performance schema was deleted on your system and manually created with the same name. I would recommend that you restore the default power plans with command `powercfg -restoredefaultschemes` (you need to run command line as administrator). Be careful, this command will reset the settings of all other schemes, the sleep time setting and the power button action setting.
Battery Mode identifies power schemes by their GUID rather than their name, and displays all unknown schemes in one color.

**Comment by madgoatz** [comment]
Oh okay... yeah, Ultimate Performance randomly appeared for a day & disappeared after some months ago... recently I manually added it... 
I just tried that restoredefaultschemes command and the ultimate performance disappeared again... so i'll try to figure something out...
anyways, thanks for your response...
